Move of the files have been successfully processed with these scripts

diff --git a/post-podcasts b/post-podcasts
--- a/post-podcasts
+++ b/post-podcasts
@@ -19,7 +19,7 @@
 #for src_file in $(ls "$src_dir"); do
 
 
-script_name=$(basename "$0")
+script_name="$(basename "$0")"
 usage() {
     echo -e "Usage: ${script_name} /PATH/TO/OUTPUT_FILE_FROM_UPLOAD_SCRIPT\n"
     echo -e "expect file to be csv\nexpect each file line to have 2 fields\nexpect field 1 to be the full file path\nexpect filed 2 to be the upload url"
@@ -67,41 +67,42 @@ while IFS='' read -r line; do
         #echo -e "\nsrc_file is $src_file\n"
 
         #Create variables of ID3 tags.
-        post_title=$( eyeD3 --plugin=display -p "%t%" "$src_file" 2> /dev/null)
-        post_date=$( eyeD3 --plugin=display -p "%original-release-date%" "$src_file" 2> /dev/null)
-        post_album=$( eyeD3 --plugin=display -p "%A%" "$src_file" 2> /dev/null)
-        post_track_num=$(  eyeD3 --plugin=display -p "%n%" "$src_file" 2> /dev/null)   
+        post_title="$(eyeD3 --plugin=display -p "%t%" "$src_file" 2> /dev/null)"
+        post_date="$(eyeD3 --plugin=display -p "%original-release-date%" "$src_file" 2> /dev/null)"
+        post_album="$(eyeD3 --plugin=display -p "%A%" "$src_file" 2> /dev/null)"
+        post_track_num="$(eyeD3 --plugin=display -p "%n%" "$src_file" 2> /dev/null)"   
 
         if [[ -n "$post_title" ]] && [[ -n "$post_album" ]] && [[ -n "$post_track_num" ]] && [[ -n "$post_date" ]]; then
-            post_description=$( eyeD3 --plugin=display -p "%c%" "$src_file" 2> /dev/null)
+            post_description="$(eyeD3 --plugin=display -p "%c%" "$src_file" 2> /dev/null)"
             #Insure date is in the format:YYYY-MM-DD with a catch-all.
             #echo -e "\nactive date in question: $post_date"
             echo $post_date | egrep -q '[0-9]{4}-[0-9]{2}-[0-9]{2}'
-            exitstatus=$?
+            exitstatus="$?"
 
             if [[ $exitstatus -ne 0 ]]; then
                 #echo "$post_date didn't match accepted format"
-                    post_date=$( date "+%Y-%m-%d" )
+                    post_date="$(date "+%Y-%m-%d")"
                 else
                     #echo "format seemed okay. trying ''date'' on $post_date"
                 date "+%Y-%m-%d" -d "$post_date" > /dev/null  2>&1
-                date_exitstatus=$?
+                date_exitstatus="$?"
 
                     if [[ $date_exitstatus -eq 1 ]]; then
                         #echo "date seemed to think $post_date isn't a real date"
-                        post_date=$( date "+%Y-%m-%d" )
+                        post_date="$(date "+%Y-%m-%d")"
                     fi
             fi
             #echo "at the end, our date is: $post_date"
 
-            post_year=$( echo $post_date | egrep -o '[0-9]{4}' )
+            post_year="$(echo $post_date | egrep -o '[0-9]{4}')"
             #echo "this is just the year: $post_year"
 
-            #podcast_name=$( eyeD3 --plugin=display -p "%a%" "$src_file" 2> /dev/null)
+            post_artist="$(eyeD3 --plugin=display -p "%a%" "$src_file" 2> /dev/null)"
+            post_artist_lcns="$(echo "$post_artist" | sed -e 's/./\L&/g; s/ /-/g')"
 
-            podcast_name_lcns=$( echo "$post_album" | sed -e 's/./\L&/g; s/ /-/g' )
+            podcast_name_lcns="$( echo "$post_album" | sed -e 's/./\L&/g; s/ /-/g')"
             #echo "podcast_name_lcns is: $podcast_name_lcns"
-            taxonomy_child_term=$( echo "$post_year"-"$podcast_name_lcns" )
+            taxonomy_child_term="$(echo "$post_year"-"$podcast_name_lcns")"
                     
 
             #List of variables of podcast thumbnail images
@@ -113,12 +114,12 @@ while IFS='' read -r line; do
                     wp_thumbnail="1502"
                     ;; 
                 "chip")
-                wp_thumbnail="1668"
-                ;;
+                    wp_thumbnail="1668"
+                    ;;
                 "education-currents")
-                wp_thumbnail="1523"
-                ;;
-                "health-longevity")
+                    wp_thumbnail="1523"
+                    ;;
+                "health-and-longevity")
                     wp_thumbnail="1541"
                     ;;
                 "heartwise")
@@ -128,23 +129,24 @@ while IFS='' read -r line; do
                     wp_thumbnail="1547"
                     ;;
                 "lifequest")
-                wp_thumbnail="1572"
-                ;;
+                    wp_thumbnail="1572"
+                    ;;
                 "lifequest-liberty")
-                wp_thumbnail="1670"
-                ;;
+                    wp_thumbnail="1670"
+                    ;;
                 "message-of-hope")
-                wp_thumbnail="2063"
-                ;;
+                    wp_thumbnail="2063"
+                    ;;
                 "sink-the-beagle")
-                wp_thumbnail="1650"
-                ;;
+                    wp_thumbnail="1650"
+                    ;;
                 "someone-cares-prison-ministry")
-                wp_thumbnail="1613"
-                ;;
+                    wp_thumbnail="1613"
+                    ;;
                 *)
-                echo "Error! Name doesn't match!"
-                ;;
+                    echo "Error! Name doesn't match!"
+                    echo "Error! Name doesn't match!" >> $logfile
+                    ;;
             esac
 
             #echo $src_file
@@ -153,7 +155,7 @@ while IFS='' read -r line; do
     #        wp_meta=$( echo "--meta_input='{\"enclosure\":\""https://s3.us-east-2.amazonaws.com/ltrpodcasts/education-currents/2018/Godspeed-Voices-of-the-Reformation-David-Teems.mp3"\",\""_thumbnail_id"\":\""$wp_thumbnail"\"}'" )	
 
     ## randall modified wp_meta
-            wp_meta=$(echo "--meta_input='{\"enclosure\":\""$file_url"\",\""_thumbnail_id"\":\""$wp_thumbnail"\"}'")	
+            wp_meta="$(echo "--meta_input='{\"enclosure\":\""$file_url"\",\""_thumbnail_id"\":\""$wp_thumbnail"\"}'")"
 
             #SSH into dev server and create new post of podcast episode.
          #   echo "wp post create --post_content=\"$post_description\" --post_title=\"$post_title\" --post_date=\"$post_date\" --post_status=publish --post_type=podcasts $wp_meta --porcelain --path=/var/www/html/lifetalk.net/public_html/"
@@ -163,14 +165,23 @@ while IFS='' read -r line; do
             #ssh "$whole_line"
 
             #echo "FAKE wp_post" >> $logfile
-            wp_post=$(ssh wp_cli_user@172.16.208.18 -i ~/id_wp_cli_user_rsa "wp post create --post_content=\"$post_description\" --post_title=\"$post_title\" --post_date=\"$post_date\" --post_status=publish --post_type=podcasts $wp_meta --porcelain --path=/var/www/html/lifetalk.net/public_html/" < /dev/null)
+            wp_post="$(ssh wp_cli_user@172.16.208.18 -i ~/id_wp_cli_user_rsa "wp post create --post_content=\"$post_description\" --post_title=\"$post_title\" --post_date=\"$post_date\" --post_status=publish --post_type=podcasts $wp_meta --porcelain --path=/var/www/html/lifetalk.net/public_html/" < /dev/null)"
         #echo -e "\nwp_post is this: $wp_post\n"
 
         #echo "last $src_file"
         #Add taxonomy terms to new post.
         #echo "FAKE ssh" >> $logfile
-            ssh wp_cli_user@172.16.208.18 -i ~/id_wp_cli_user_rsa "wp post term add $wp_post podcasts_cat $podcast_name_lcns $taxonomy_child_term  --path=/var/www/html/lifetalk.net/public_html/" < /dev/null > /dev/null
+            if [[ "$podcast_name_lcns" == "message-of-hope" ]] || [[ "$podcast_name_lcns" == "chip" ]]; then
+
+                ssh wp_cli_user@172.16.208.18 -i ~/id_wp_cli_user_rsa "wp post term add $wp_post post_tag $post_artist_lcns --path=/var/www/html/lifetalk.net/public_html/" < /dev/null > /dev/null
+                ssh wp_cli_user@172.16.208.18 -i ~/id_wp_cli_user_rsa "wp post term add $wp_post podcasts_cat $podcast_name_lcns $taxonomy_child_term  --path=/var/www/html/lifetalk.net/public_html/" < /dev/null > /dev/null
+
+            else
+                ssh wp_cli_user@172.16.208.18 -i ~/id_wp_cli_user_rsa "wp post term add $wp_post podcasts_cat $podcast_name_lcns $taxonomy_child_term  --path=/var/www/html/lifetalk.net/public_html/" < /dev/null > /dev/null
+            fi
+
             echo "$src_file" >> "$logfile"
+
         else
             echo "$src_file" >> "$skipped_file"
         fi
diff --git a/upload-podcasts b/upload-podcasts
--- a/upload-podcasts
+++ b/upload-podcasts
@@ -12,16 +12,9 @@ converted_dir="${project_dir}/converted"
 
 inc_pattern="^.*\.(mp3|mp2|wav|docx|doc|aif|MP3|MP2|WAV|DOCX|DOC|AIF)$"
 
-skipped_file="${logs_dir}/skipped"
 
 ## In order to generate logs for each show during a single script execution
 ## the primary log config happens within main()
-
-if [[ -f "$skipped_file" ]]; then
-    mv "$skipped_file" "${skipped_file}_$(date +%Y%m%d_%H%M)"
-fi
-#touch "$skipped_file"
-#echo -e "**** $(date +%Y%m%d_%H%M) ****" >> "$skipped_file"
 
 expected_file="${logs_dir}/expected"
 if [[ -f "$expected_file" ]]; then
@@ -38,28 +31,37 @@ fi
 #echo -e "**** $(date +%Y%m%d_%H%M) ****" >> "$copied_file"
 
 declare -A dir_array
-## Comment/uncomment these elements to iterate and upload these shows
+## Comment/uncomment these to select which directors the script will run on 
+## i.e. to select which shows to upload or not
+
 dir_array[ail]="ail" #"American Indian Living"
 dir_array[bt]="bt" #"Bible Talk"
 dir_array[ec]="ec" #"Education Currents"
 dir_array[hal]="hal" #"Health and Longevity"
-## TODO
-## CHIP; create chip dir, move HBC and CHIP into it
-#dir_array[chip]="chip" #"Healthy By Choice"
+dir_array[hbc]="hbc" #"Healthy By Choice"
+## chip shouldn't need to be explicitly run because it's already
+## a sub folder of hbc
+#dir_array[chip]="hbc/chip_health" #"Healthy By Choice"
 dir_array[hm]="hm" #"Heartwise Ministries"
 dir_array[hc]="hc" #"Homeschool Companion"
 dir_array[lqa]="lqa" #"LifeQuest - Authors"
 ## LQLFAL is not needed
 dir_array[lql]="lql" #"LifeQuest Liberty"
 dir_array[moh]="moh" #"Message of Hope"
-#dir_array[scpm]="scpm" #"Someone Cares Prison Ministry"
+dir_array[scpm]="scpm" #"Someone Cares Prison Ministry"
 dir_array[stb]="stb" #"Sink The Beagle"
 
 declare -A s3_show_dir_array
-## The values in this array can be used to alter the show directory in the S3 Dest URL
+## The values in this array can be used to alter the directory names in the S3 Dest URL for each show 
+
+## Chip and Healthy by Choice files are to be slightly re-arranged at the time of upload
+## converted has /hbc and /hbc/chip_health
+## on upload those should become /chip/(containing hbc*.mp3) and /chip/(chip*.mp3 from chip_health)
+s3_show_dir_array[hbc]="chip" # "Healthy by Choice" files are moved to chip
+s3_show_dir_array[chip]="chip" # "CHIP Health" filed moved out of chip_health into parent
+
 s3_show_dir_array[ail]="ail" #"American Indian Living"
 s3_show_dir_array[bt]="bt" #"Bible Talk"
-s3_show_dir_array[chip]="chip" #"Healthy By Choice"
 s3_show_dir_array[ec]="ec" #"Education Currents"
 s3_show_dir_array[hal]="hnl" #"Health and Longevity"
 s3_show_dir_array[hm]="hw" #"Heartwise Ministries"
@@ -70,6 +72,10 @@ s3_show_dir_array[moh]="moh" #"Message of Hope"
 s3_show_dir_array[stb]="sb" #"Sink The Beagle"
 s3_show_dir_array[scpm]="scpm" #"Someone Cares Prison Ministry"
 
+declare -A  s3_file_name_array
+## placeholder for later function pulling ls from s3
+## made associative for faster searching
+
 skip_file() {
     # Arguments:
     # $1 -> $src_file
@@ -79,7 +85,7 @@ skip_file() {
     skipped_reason="$2"
     #echo "skip_file()"
 
-    echo "Skipping..."
+    #echo "Skipping..."
     echo "[$skipped_reason] $src_file"  >>  "$skipped_file"
 
 }
@@ -161,9 +167,6 @@ test_year() {
         fi
     fi
 
-    ## testing
-    #echo "$received:$tag_year"
-
     echo "$tag_year"
 }
 
@@ -195,6 +198,7 @@ compose_upload_path() {
     echo "$upload_path"
 }
 
+
 upload_files() {
     # Arguments:
     # 1 -> src_dir
@@ -202,44 +206,77 @@ upload_files() {
     src_dir="$1"
     key="$2"
 
+    show_dir_on_s3="${s3_show_dir_array[$key]}"
+
+    s3_file_list="s3_file_list_${key}"
+
+    if [[ -f $s3_file_list ]]; then
+        echo "$s3_file_list found. Removing"
+        rm "$s3_file_list"
+    fi
+
+    touch s3_file_list || echo "failed to create $s3_file_list" >> $logfile
+    
+    ## pulling a file list from aws
+    aws s3 ls s3://ltrpodcasts/${show_dir_on_s3} --recursive > $s3_file_list 2>$logfile
+    
+    mycount=0
+    while IFS= read -r line; do
+        s3_file_name="$(echo "$line" | awk 'BEGIN{FS=OFS="/"}{ print $(NF) }')"
+
+        s3_file_name_array[${s3_file_name}]="${mycount}"
+        (( mycount++ ))
+
+    done < "$s3_file_list"
+
     find "$src_dir" -type f -print0 |
       while IFS= read -r -d $'\0' src_file; do
-        
-        #echo "$key"
-        #echo "array:${s3_show_dir_array[@]}"
-        #echo "value:${s3_show_dir_array[$key]}"
-        ## retrieve date info from id3 tag
-        date_from_file="$(get_year "$src_file")"
 
-        ## use id3 tag date to get a valid year
-        file_year="$(test_year "$date_from_file")"
+        file_name="$(echo "$src_file" | awk 'BEGIN{FS=OFS="/"}{ print $(NF) }')"
 
-        ## create destination
+        ## returns exit 0 if the array key as a non-zero sized element 
+        ## if the array key has been created above 
+        ## the filename existed in the list pulled from ls
+        ## if the key exists, the file is already on s3
+        ##    [[ -n "${s3_file_name_array["$file_name"]}" ]] && printf '%sfound\n' "$i"
 
-        #echo "passing:"$file_year" "${s3_show_dir[$key]}""
-        #echo "$src_file"
-        upload_path="$(compose_upload_path "$src_file" "${s3_show_dir_array[$key]}" "$file_year")"
-        #echo "$upload_path"
+        if [[ -n "${s3_file_name_array["$file_name"]}" ]]; then
+            skip_file "$src_file" "exists on s3"
+        else
 
-        ##  adding here s3://
-        modded_upload_path="s3://${upload_path}"
+            ## retrieve date info from id3 tag
+            date_from_file="$(get_year "$src_file")"
 
-        aws s3 cp --only-show-errors "$src_file" "$modded_upload_path" >> "$logfile"
-        aws_cmd_exit_status="$?"
+            ## use id3 tag date to get a valid year
+            file_year="$(test_year "$date_from_file")"
 
-        site_hostname="https://s3.us-east-2.amazonaws.com"
-        url_for_output="${site_hostname}/${upload_path}"
+            upload_path="$(compose_upload_path "$src_file" "${s3_show_dir_array[$key]}" "$file_year")"
+            echo "$upload_path"
 
-        if [[ $aws_cmd_exit_status == 0 ]]; then
-            echo "aws success: $src_file" >> $logfile
-            echo "${src_file},${url_for_output}" >> "$uploaded_file"
-        else 
-            echo "aws failed : $aws_cmd_exit_status : $src_file" >> $logfile
+            ##  adding here s3://
+            modded_upload_path="s3://${upload_path}"
+            
+
+            ## testing. Without this aws line, nothing gets uploaded
+            aws s3 cp --only-show-errors "$src_file" "$modded_upload_path" >> "$logfile"
+
+            aws_cmd_exit_status="$?"
+
+            site_hostname="https://s3.us-east-2.amazonaws.com"
+            url_for_output="${site_hostname}/${upload_path}"
+
+            if [[ $aws_cmd_exit_status == 0 ]]; then
+                echo "aws success: $src_file" >> $logfile
+                echo "${src_file},${url_for_output}" >> "$uploaded_file"
+            else 
+                echo "aws failed : $aws_cmd_exit_status : $src_file" >> $logfile
+            fi
         fi
- 
 
-done
 
+      done
+
+      rm "$s3_file_list"
 }
 
 main() {
@@ -262,6 +299,15 @@ main() {
 
         echo -e "**** $(date +%Y%m%d_%H%M) ****" >> "$uploaded_file"
 
+        skipped_file="${logs_dir}/skipped_${key}"
+        if [[ -f "$skipped_file" ]]; then
+            mv "$skipped_file" "${skipped_file}_$(date +%Y%m%d_%H%M)"
+        fi
+        touch "$skipped_file"
+        echo -e "**** $(date +%Y%m%d_%H%M) ****" >> "$skipped_file"
+
+        ## testing log file with no key
+        #logfile="${logs_dir}/${script_name}"
         logfile="${logs_dir}/${script_name}_${key}"
 
         if [[ -f "$logfile" ]]; then
